/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: e7b682ee062bb40ec62cebe3afe3e571)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	TURN_RATE_LIMITER: RateLimit;
	DEBRIEF_RATE_LIMITER: RateLimit;
	MODEL_MODE: "live";
	MODEL_BASE_URL: "https://api.deepseek.com";
	MODEL_NAME: "deepseek-v4-flash";
	ASSISTANT_HOURLY_LIMIT: "5";
	ASSISTANT_DAILY_LIMIT: "25";
	PROMPT_VERSION: "2026-08-26.1";
	POLICY_VERSION: "2026-08-26.1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL_MODE" | "MODEL_BASE_URL" | "MODEL_NAME" | "ASSISTANT_HOURLY_LIMIT" | "ASSISTANT_DAILY_LIMIT" | "PROMPT_VERSION" | "POLICY_VERSION">> {}
}
