/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 9068711ff39b71d3efce119cef2a6fc0)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	TURN_RATE_LIMITER: RateLimit;
	DEBRIEF_RATE_LIMITER: RateLimit;
	MODEL_MODE: "mock";
	PROMPT_VERSION: "2026-08-26.1";
	POLICY_VERSION: "2026-08-26.1";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL_MODE" | "PROMPT_VERSION" | "POLICY_VERSION">> {}
}
